version: 2.1

orbs:
  win: circleci/windows@2.2.0

exclude_master: &exclude_master
  filters:
    branches:
      ignore: master

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.oqsjob: &oqsjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Configure
        command: mkdir build && cd build && source ~/.bashrc && cmake -GNinja ${CONFIGURE_ARGS} .. && cmake -LA ..
    - run:
        name: Build
        command: ninja
        working_directory: build
    - run:
        name: Run tests
        command: ninja run_tests
        working_directory: build
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: build/test-results
    - store_artifacts:
        path: build/test-results

.emulatedjob: &emulatedjob
  machine:
    image: ubuntu-1604:201903-01
  steps:
    - checkout
    - run:
        name: Install the emulation handlers
        command: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    - run:
        name: Run the tests in a container
        command: |
          docker run -e SKIP_TESTS=style --rm -v `pwd`:`pwd` -w `pwd` openquantumsafe/ci-debian-buster-${ARCH}:latest /bin/bash -c "
          uname -a &&
          file /bin/ls &&
          mkdir build &&
          (cd build &&
          cmake -GNinja ${CONFIGURE_ARGS} .. &&
          cmake -LA .. &&
          ninja &&
          ninja run_tests)
          "
    - store_test_results:
        path: build/test-results
    - store_artifacts:
        path: build/test-results

.macjob: &macjob
    macos:
        xcode: "11.3.0"
    steps:
        - checkout
        - run:
            name: Install dependencies
            command: |
              scripts/git_no_checkin_in_last_day.sh || (
              brew update &&
              brew unlink python@2 &&
              brew install cmake ninja doxygen astyle &&
              pip3 install pytest pytest-xdist
              )
        - run:
            name: Configure
            command: mkdir build && cd build && cmake -GNinja ${CONFIGURE_ARGS} .. && cmake -LA ..
        - run:
            name: Build
            command: ninja
            working_directory: build
        - run:
            name: System information
            command: sysctl -a | grep machdep.cpu
        - run:
            name: Run tests
            command: ninja run_tests
            working_directory: build
        - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
            path: build/test-results
        - store_artifacts:
            path: build/test-results

jobs:
  centos-7-amd64:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-centos-7-amd64:latest
      CONFIGURE_ARGS: -DOPENSSL_ROOT_DIR=/usr/local/ssl
      SKIP_TESTS: style
  centos-8-amd64:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-centos-8-amd64:latest
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Release -DOQS_PORTABLE_BUILD=OFF
      CC: clang
      SKIP_TESTS: style
  debian-buster-amd64:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-debian-buster-amd64:latest
      SKIP_TESTS: style
  debian-buster-arm64:
    <<: *emulatedjob
    environment:
      ARCH: arm64
      CONFIGURE_ARGS: -DOQS_ENABLE_SIG_SPHINCS=OFF # sig-sphincs exhausts memory on CircleCI servers
  debian-buster-armhf:
    <<: *emulatedjob
    environment:
      ARCH: armhf
      CONFIGURE_ARGS: -DOQS_ENABLE_SIG_SPHINCS=OFF # sig-sphincs exhausts memory on CircleCI servers
  debian-buster-armel:
    <<: *emulatedjob
    environment:
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Release -DOQS_ENABLE_SIG_SPHINCS=OFF # sig-sphincs exhausts memory on CircleCI servers
      ARCH: armel
  alpine-amd64-static:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-alpine-amd64:latest
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Release -DOQS_USE_OPENSSL=OFF
      SKIP_TESTS: style,doxygen # not installed in alpine, no news anyway
  alpine-amd64-shared:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-alpine-amd64:latest
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Release -DOQS_USE_OPENSSL=ON -DBUILD_SHARED_LIBS=ON
      SKIP_TESTS: style,doxygen # not installed in alpine, no news anyway
  ubuntu-bionic-x86_64-gcc8:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      CC: gcc-8
  ubuntu-bionic-x86_64-gcc7-noopenssl:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      CC: gcc-7
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Release -DOQS_USE_OPENSSL=OFF
  ubuntu-bionic-x86_64-gcc7-shared:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      CC: gcc-7
      CONFIGURE_ARGS: -DBUILD_SHARED_LIBS=ON
      #TODO: _init and _fini trip test_namespace.py
      SKIP_TESTS: namespace
  ubuntu-bionic-x86_64-clang9:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      CC: clang-9
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Release -DOQS_PORTABLE_BUILD=OFF
  ubuntu-bionic-x86_64-asan:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      CC: clang-9
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DUSE_SANITIZER=Address
  ubuntu-bionic-x86_64-ubsan:
    <<: *oqsjob
    environment:
      IMAGE: openquantumsafe/ci-ubuntu-bionic-x86_64:latest
      CC: clang-9
      CONFIGURE_ARGS: -DCMAKE_BUILD_TYPE=Debug -DUSE_SANITIZER=Undefined
      RUN_TESTS_PARALLEL: FALSE
  macOS-static-noopenssl:
    <<: *macjob
    environment:
        CONFIGURE_ARGS: -DOQS_USE_OPENSSL=OFF
        SKIP_TESTS: style,doxygen
  macOS-shared-openssl:
    <<: *macjob
    environment:
        CONFIGURE_ARGS: -DOQS_USE_OPENSSL=ON -DBUILD_SHARED_LIBS=ON
        RUN_TESTS_PARALLEL: FALSE
        SKIP_TESTS: style,doxygen
  trigger-downstream-ci:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run:
          name: Trigger OQS-OpenSSL CI
          command: |
            curl -u ${BUILD_TRIGGER_TOKEN}: -X POST --header "Content-Type: application/json" -d '{"branch": "OQS-OpenSSL_1_1_1-stable"}' https://circleci.com/api/v2/project/gh/open-quantum-safe/openssl/pipeline
      - run:
          name: Trigger OQS-BoringSSL CI
          command: |
            curl -u ${BUILD_TRIGGER_TOKEN}: -X POST --header "Content-Type: application/json" -d '{"branch": "master"}' https://circleci.com/api/v2/project/gh/open-quantum-safe/boringssl/pipeline
      - run:
          name: Trigger OQS-OpenSSH CI
          command: |
            curl -u ${BUILD_TRIGGER_TOKEN}: -X POST --header "Content-Type: application/json" -d '{"branch": "OQS-master"}' https://circleci.com/api/v2/project/gh/open-quantum-safe/openssh/pipeline

workflows:
  version: 2
  build:
    jobs:
      - centos-7-amd64:
          <<: *exclude_master
      - centos-8-amd64:
          <<: *exclude_master
      - debian-buster-amd64:
          <<: *exclude_master
      - debian-buster-arm64:
          <<: *exclude_master
      - debian-buster-armhf:
          <<: *exclude_master
      - debian-buster-armel:
          <<: *exclude_master
      - ubuntu-bionic-x86_64-gcc7-noopenssl:
          <<: *exclude_master
      - ubuntu-bionic-x86_64-gcc7-shared:
          <<: *exclude_master
      - ubuntu-bionic-x86_64-gcc8:
          <<: *exclude_master
      - ubuntu-bionic-x86_64-clang9:
          <<: *exclude_master
      - alpine-amd64-static:
          <<: *exclude_master
      - alpine-amd64-shared:
          <<: *exclude_master
      - macOS-static-noopenssl:
          <<: *exclude_master
      - macOS-shared-openssl:
          <<: *exclude_master
      - ubuntu-bionic-x86_64-asan:
          <<: *exclude_master
      - trigger-downstream-ci:
          context: openquantumsafe
          filters:
            branches:
              only: master
